### ISSUE TITLE
reproducing Language Modeling results

### ISSUE THREAD

**Issue by Golovneva** [apple/ml-sigmoid-attention#4]
Hi! Thank you for releasing the code.
In the [paper](https://arxiv.org/pdf/2409.04431) you report training Llama2 recipe on 300M tokens of RedPajama dataset. However, in your code I only found examples with Wikitext. Since RedPajama dataset is quite large with 50.6T estimated tokens, I was wondering how did you select 300M tokens for training?

**Comment by jramapuram** [comment]
Hi there, thanks for the interest. We didn't use this code for the 1B results. Take a look at the axlearn code for this: https://github.com/apple/axlearn/blob/main/axlearn/experiments/text/gpt/pajama_sigmoid_trainer.py

**Comment by Golovneva** [comment]
Thanks a lot!
